
services:
  minio:
    image: minio/minio:RELEASE.2024-03-30T09-41-56Z
    volumes:
      - minio_data:/data
    expose:
      - 9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    entrypoint:
      - "sh"
      - "-c"
      - >-
        mkdir -p
        /data/test-bucket
        && minio server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  minio_data:

